//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditCardAPI.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CreditcardDBEntities : DbContext
    {
        public CreditcardDBEntities()
            : base("name=CreditcardDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditCard> CreditCards { get; set; }
    
        public virtual ObjectResult<ValidateCreditCard_Result> ValidateCreditCard(string p_CARDNUMBER, string p_EXPRIRYDATE)
        {
            var p_CARDNUMBERParameter = p_CARDNUMBER != null ?
                new ObjectParameter("P_CARDNUMBER", p_CARDNUMBER) :
                new ObjectParameter("P_CARDNUMBER", typeof(string));
    
            var p_EXPRIRYDATEParameter = p_EXPRIRYDATE != null ?
                new ObjectParameter("P_EXPRIRYDATE", p_EXPRIRYDATE) :
                new ObjectParameter("P_EXPRIRYDATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ValidateCreditCard_Result>("ValidateCreditCard", p_CARDNUMBERParameter, p_EXPRIRYDATEParameter);
        }
    }
}
